# Determinant

In [1]:
import numpy as np

## Linearly independent matrix determinant

In [4]:
A = np.random.randn(2, 2)

print(A)
print(np.linalg.det(A))

[[ 0.66506226 -0.44169975]
 [-0.54624859  0.84358644]]
0.31975963729005014


## Linearly dependent matrix determinant

In [5]:
A = np.array([
    [1, 3],
    [1, 3]
])

print(A)
print(np.linalg.det(A))

[[1 3]
 [1 3]]
0.0


## Rank and determinant from a matrix with linearly dependent set

In [9]:
m = 3
A = np.random.randn(m, m)

# Impose linear dependency
A[:, 0] = A[:, 1]

print('Matrix')
print(np.round(A, 1))
print()
print(f'Rank: {np.linalg.matrix_rank(A)}')
print('Rank is not full-rank, because of linear dependency')
print()
print(f'Determinant: {np.linalg.det(A)}')
print('Determinant is 0 because of linear dependency')

Matrix
[[ 0.7  0.7 -0.6]
 [-0.8 -0.8 -0.6]
 [ 1.1  1.1 -0.4]]

Rank: 2
Rank is not full-rank, because of linear dependency

Determinant: -1.0371662519785668e-16
Determinant is 0 because of linear dependency


## Swap rows effect on determinant

In [6]:
m = 6
A = np.random.randn(m, m)

print('A')
print(A.shape)
print(np.round(A, 1))
print()

print(f'Before row swap determinant: {np.linalg.det(A)}')
print()

# Swap row 0 and row 1
As = A[[1, 0, 2, 3, 4, 5], :]
print(f'After 1 row swap determinant: {np.linalg.det(As)}')
print('1 row swap flips the sign, but does not change the magnitude')
print()

# Swap row 3 and row 4
Ass = A[[1, 0, 2, 4, 3, 5], :]
print(f'After 2 row swaps determinant: {np.linalg.det(Ass)}')
print('2 row swaps turn the sign back to the original')

A
(6, 6)
[[ 0.7  1.4 -0.3  1.   0.7  0.1]
 [ 0.3  0.3 -0.   0.1 -0.1  0.3]
 [ 0.8 -0.1  2.9  1.  -1.8  0.2]
 [-1.5  0.5 -0.2 -1.2  0.4 -0.6]
 [-1.1 -1.6  1.5  0.8 -1.6 -0.1]
 [-2.  -0.9  0.3 -0.7 -1.7 -0.5]]

Before row swap determinant: 3.0245933712182347

After 1 row swap determinant: -3.0245933712182347
1 row swap flips the sign, but does not change the magnitude

After 2 row swaps determinant: 3.0245933712182347
2 row swaps turn the sign back to the original
