# Echelon Form

In [1]:
import numpy as np
from sympy import Matrix

## Reduced row echelon form

### Square matrix

In [17]:
a = np.random.randn(4, 4)
A = Matrix(a)
print('Original matrix')
print(np.round(a, 1))
print()

reduced_row_echelon_form = A.rref()

print('Reduced_row_echelon_form')
print(np.array(reduced_row_echelon_form[0]))

Original matrix
[[ 0.1 -2.3  1.1 -0.4]
 [-0.7  0.3 -0.7  0.6]
 [-0.8  0.4 -0.8 -0. ]
 [-0.7 -0.9  0.5 -0.6]]

Reduced_row_echelon_form
[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


### Tall matrxi

In [19]:
m = 8
n = 3
A = np.random.randn(m, n)
print('Original matrix')
print(np.round(A, 1))
print()

print('Reduced row echelon form')
print(np.array(Matrix(A).rref()[0]))

Original matrix
[[ 0.3  0.4  0.1]
 [ 0.4  1.6 -0.6]
 [-1.3 -0.3 -0.6]
 [ 0.9 -1.2 -0.3]
 [ 0.5  0.5  0.9]
 [ 0.7  1.9  0.9]
 [ 0.3  0.9  1.9]
 [-0.7  2.7  0.4]]

Reduced row echelon form
[[1 0 0]
 [0 1 0]
 [0 0 1]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]


### Wide matrix

In [54]:
m = 3
n = 8
A = np.random.randn(m, n)
print('Original matrix')
print(np.round(A, 1))
print()

print('Reduced row echelon form')
A = np.array(Matrix(A).rref()[0])
for row in range(len(A)):
    for col in range(len(A[0])):
        print(round(A[row, col]), end='\t')
    print('\r')

Original matrix
[[-2.4 -1.6 -1.7  0.9 -0.1  0.2 -1.  -0.4]
 [-0.2  0.9  0.1  1.2  1.3 -1.1 -1.  -0.1]
 [ 0.5 -1.5  1.3 -1.6  0.2  0.1  1.  -0.2]]

Reduced row echelon form
1	0	0	-1	-2	1	1	0	
0	1	0	1	1	-1	-1	0	
0	0	1	0	2	-1	-1	0	


### Linear dependency

In [59]:
a = np.random.randn(5, 5)
a[:, 0] = a[:, 1]
A = Matrix(a)
print('Original matrix')
print(np.round(a, 1))
print()

print('Reduced_row_echelon_form')
A = np.array(Matrix(A).rref()[0])
for row in range(len(A)):
    for col in range(len(A[0])):
        print(round(A[row, col]), end='\t')
    print('\r')
print()
print('1 at row 0 and col 1 is not pivot')

Original matrix
[[ 1.8  1.8  0.6 -1.1 -1.5]
 [ 0.5  0.5  0.3  0.1  0.5]
 [ 0.1  0.1 -0.8  1.2 -0.5]
 [ 0.9  0.9  0.2 -0.  -0.6]
 [ 0.9  0.9  0.4 -0.7  0. ]]

Reduced_row_echelon_form
1	1	0	0	0	
0	0	1	0	0	
0	0	0	1	0	
0	0	0	0	1	
0	0	0	0	0	

1 at row 0 and col 1 is not pivot
