# Eigendecomposition

## Dependency

In [1]:
import numpy as np
import matplotlib.pyplot as plt

## Application of eigendecomposition

- Principal component analysis
- Regularization such as ridge regression
- Linear discriminant analysis
- Support vector machine

So you need to understand eigendecomposition.

## Eigenvalue

$$ A v = \lambda v $$
$$ A v - \lambda v = 0 $$
$$ (A - \lambda I) v = 0 $$

We cannot do $(A - \lambda) v$, because $A$ is a matrix, but $\lambda$ is a scalar.

$(A - \lambda I) v = 0$ means that a vector $v$ is in the **null space** of a matrix $A$ shifted by $-\lambda I$, because it's producting 0 vector. $B v = 0$ means $v$ is in the **null space** of a matrix $B$.

In eigendecomposition, we exclude a case where $v$ is a vector of all 0s. $v$ needs to have at least one element non-zero. So to produce 0 at the right side of the equation, $(A - \lambda I)$ must be a **singular matrix** (**reduced rank matrix**). If $(A - \lambda I)$ is a singular matrix, it means that a **determinant** of $(A - \lambda I)$ is 0.

$$ |A - \lambda I| = 0 $$

In $(A - \lambda I) v = 0$, $0$ is a 0 vector, but in $|A - \lambda I| = 0$, $0$ is a scalar 0. $|A - \lambda I| = 0$ is called **characteristic equation**.

## Eigenvalue of diagonal matrix

Eigenvalues of a diagonal matrix are diagonal elements of the diagonal matrix. For example,

$$
A = 
\begin{bmatrix}
1 & 0\\
0 & 2
\end{bmatrix}
$$

$$
\begin{vmatrix}
1 - \lambda & 0\\
0 & 2 - \lambda
\end{vmatrix}
= 0
$$

$$
(1 - \lambda)(2 - \lambda) = 0
$$

$$
\lambda = 1, 2
$$

So we can imagine that, even if a diagonal matrix gets bigger, off-diagonal elements will disappear from **characteristic equations** and it gives us a bunch of $(d_i - \lambda) = 0$, so we can directly use diagonal elements as eigenvalues.

In [5]:
A = np.diag(np.arange(1, 10 + 1))

print('Diagonal matrix')
print(A)
print()

eigen_values = np.linalg.eig(A)[0]
print('Eigenvalues of diagonal matrix')
print(eigen_values)
print()

Diagonal matrix
[[ 1  0  0  0  0  0  0  0  0  0]
 [ 0  2  0  0  0  0  0  0  0  0]
 [ 0  0  3  0  0  0  0  0  0  0]
 [ 0  0  0  4  0  0  0  0  0  0]
 [ 0  0  0  0  5  0  0  0  0  0]
 [ 0  0  0  0  0  6  0  0  0  0]
 [ 0  0  0  0  0  0  7  0  0  0]
 [ 0  0  0  0  0  0  0  8  0  0]
 [ 0  0  0  0  0  0  0  0  9  0]
 [ 0  0  0  0  0  0  0  0  0 10]]

Eigenvalues of diagonal matrix
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]



## Eigenvalue of triangular matrix

Eigenvalues of a triangular matrix has the same result as a diagonal matrix. That is, regardless of upper triangular matrix or lower triangular matrix, eigenvalues will be diagonal elements of the triangular matrix. For example in 2x2 upper triangular matrix,

$$
A =
\begin{bmatrix}
1 & 2\\
0 & 3
\end{bmatrix}
$$

$$
\begin{vmatrix}
1 - \lambda & 2\\
0 & 3 - \lambda
\end{vmatrix}
= 0
$$

$$
(1 - \lambda)(3 - \lambda) = 0
$$

$$
\lambda = 1, 3
$$

Because when computing determinant and when making multiplication with diagonal elements, 0 at the either side of the diagonal cancels any number, so off-diagonal elements will disappear.

In [9]:
A = np.triu(np.random.randn(4, 4))

print('Upper triangular matrix')
print(np.round(A, 1))
print()

eigen_values = np.linalg.eig(A)[0]

print('Eigenvalue')
print(np.round(eigen_values, 1))
print()

Upper triangular matrix
[[-0.3  0.1  2.3 -1.8]
 [ 0.   1.1  0.4 -0.5]
 [ 0.   0.   1.  -1. ]
 [ 0.   0.   0.   0.5]]

Eigenvalue
[-0.3  1.1  1.   0.5]



In [10]:
A = np.tril(np.random.randn(4, 4))

print('Lower triangular matrix')
print(np.round(A, 1))
print()

eigen_values = np.linalg.eig(A)[0]

print('Eigenvalue')
print(np.round(eigen_values, 1))
print()

Lower triangular matrix
[[ 1.5  0.   0.   0. ]
 [-1.2  0.2  0.   0. ]
 [-0.7  0.5  0.1  0. ]
 [-1.2  1.5  1.1 -0.9]]

Eigenvalue
[-0.9  0.1  0.2  1.5]



## Eigenvector

Eigenvector is more important than eigenvector, but you need to compute eigenvalue before computing eigenvector

1. Find all eigenvalues $\lambda$
2. For each $\lambda$, find a vector $v$ which is in the **null space** of a shifted matrix by $\lambda$, $(A - \lambda I)$. That is $v \in C(A - \lambda I)$

$v$ in the null space of $(A - \lambda I)$ means that $(A - \lambda I) v$ gives us a vector with all 0s in elements. In math,

$$
(A - \lambda I) v = \textbf{0}
$$

Typically, after finding those vectors, people normalize it, meaning the vector has a unit length.

To double check the process to compute eigenvector, first find eigenvalues, and shift the original matrix by the eigenvalue, and find the **basis vector** (meaning normalized unit length vector) for the **null space** of the shifted matrix.

In [15]:
A = np.array([
    [1, 2],
    [2, 1]
])

print('Matrix')
print(A)
print()

evals, evecs = np.linalg.eig(A)

print('Eigenvector')
print(evecs)
print()

print('Eigenvalue')
print(evals)
print()

print(f'First eigenvalue: {evals[0]} has the associated eigenvector')
print(f'in first column of the eigenvector matrix: {evecs[:, 0]}')
print()

print(f'Second eigenvalue: {evals[1]} has the associated eigenvector')
print(f'in second column of the eigenvector matrix: {evecs[:, 1]}')

Matrix
[[1 2]
 [2 1]]

Eigenvector
[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]

Eigenvalue
[ 3. -1.]

First eigenvalue: 3.0000000000000004 has the associated eigenvector
in first column of the eigenvector matrix: [0.70710678 0.70710678]

Second eigenvalue: -0.9999999999999996 has the associated eigenvector
in second column of the eigenvector matrix: [-0.70710678  0.70710678]


In [16]:
# From 134 udemy