# Frobenius Dot Product

In [1]:
import numpy as np

In [17]:
m = 9
n = 4

A = np.random.randn(m, n)
B = np.random.randn(m, n)

print('A')
print(np.round(A, 1))
print()

# Vectorize by column-wise concatenation
# order='F' reshapes by columns instead of by rows (by default)
Av = np.reshape(A, m * n, order='F')
print('Av')
print(np.round(Av, 1))
print()
Bv = np.reshape(B, m * n, order='F')

# Dot product method
frob_dp1 = np.dot(Av, Bv)
print('Dot product method: Frobenius dot product 1')
print(np.round(frob_dp1, 1))
print()

# Trace method
frob_dp2 = np.trace(A.T @ B)
print('Trace method: Frobenius dot product 2')
print(np.round(frob_dp2, 1))
print()

# Matrix norm
Anorm1 = np.linalg.norm(A, ord='fro')
print('Matrix norm by Frobenius')
print(np.round(Anorm1, 1))
print()

Anorm2 = np.sqrt(np.trace(A.T @ A))
print('Matrix norm by trace')
print(np.round(Anorm2, 1))
print()

A
[[ 0.2 -1.5 -0.2  0.1]
 [ 0.7  0.1  0.4  2. ]
 [-0.7 -1.7  0.6 -1.8]
 [-0.7 -1.  -0.4 -1.2]
 [ 0.2  0.   1.2 -1.2]
 [ 1.9  0.8 -1.7  2. ]
 [-0.4 -0.5 -0.6  2. ]
 [ 0.4  1.1  0.3  0.6]
 [ 0.1 -1.5 -0.3 -0.6]]

Av
[ 0.2  0.7 -0.7 -0.7  0.2  1.9 -0.4  0.4  0.1 -1.5  0.1 -1.7 -1.   0.
  0.8 -0.5  1.1 -1.5 -0.2  0.4  0.6 -0.4  1.2 -1.7 -0.6  0.3 -0.3  0.1
  2.  -1.8 -1.2 -1.2  2.   2.   0.6 -0.6]

Dot product method: Frobenius dot product 1
-7.4

Trace method: Frobenius dot product 2
-7.4

Matrix norm by Frobenius
6.4

Matrix norm by trace
6.4

