# Matrix Multiplication

In [1]:
import numpy as np
np.random.seed(0)

## Matrix multiplication via layers
- Calculate out products and sum them

In [39]:
m = 4
n = 6
a = np.random.randn(m, n)
b = np.random.randn(n, m)

c1 = np.zeros((m, m))
for i in range(n):
    c1 += np.outer(a[:, i], b[i, :])

print('c1')
print(c1)
print()

# @ to do matrix multiplication
c2 = a @ b

print('c2')
print(c2)
print()

print('c1 - c2')
print(np.round(c1 - c2))

c1
[[ 9.25304851e-01 -2.15205779e-01 -2.73774581e-03 -4.37230744e-01]
 [-1.00483369e-01 -3.01390805e+00  1.95016457e-01 -4.20552903e+00]
 [ 2.43586067e+00 -6.68811690e-01  3.06932279e+00 -4.31307818e+00]
 [ 1.23472903e-01  5.45648522e-01 -4.12872031e-01 -2.90151481e+00]]

c2
[[ 9.25304851e-01 -2.15205779e-01 -2.73774581e-03 -4.37230744e-01]
 [-1.00483369e-01 -3.01390805e+00  1.95016457e-01 -4.20552903e+00]
 [ 2.43586067e+00 -6.68811690e-01  3.06932279e+00 -4.31307818e+00]
 [ 1.23472903e-01  5.45648522e-01 -4.12872031e-01 -2.90151481e+00]]

c1 - c2
[[ 0.  0. -0. -0.]
 [ 0.  0. -0.  0.]
 [-0.  0.  0.  0.]
 [-0.  0.  0.  0.]]


## Matrix multiplication with a diagonal matrix

In [45]:
a = np.array([
    [1, 1, 1],
    [1, 1, 1],
    [1, 1, 1]
])
d = np.diag([1, 2, 3])

print('a')
print(a)
print()

print('d')
print(d)
print()

print('a @ d scales by column')
print(a @ d)
print()

print('d @ a scales by row')
print(d @ a)
print()

a
[[1 1 1]
 [1 1 1]
 [1 1 1]]

d
[[1 0 0]
 [0 2 0]
 [0 0 3]]

a @ d scales by column
[[1 2 3]
 [1 2 3]
 [1 2 3]]

d @ a scales by row
[[1 1 1]
 [2 2 2]
 [3 3 3]]



## Order-of-operations

In [50]:
n = 2
l = np.random.randn(n, n)
i = np.random.randn(n, n)
v = np.random.randn(n, n)
e = np.random.randn(n, n)

# LIVE
a1 = np.matrix.transpose(l @ i @ v @ e)

# EVIL
a2 = e.T @ v.T @ i.T @ l.T

print(np.round(a1 - a2))

[[ 0.  0.]
 [ 0. -0.]]


## Matrix-vector multiplication

In [21]:
m = 4

# Matrix
non_symmetric = np.random.randint(-10, 11, (m, m))
print('Non-symmetric matrix')
print(non_symmetric)
print(non_symmetric.shape)
print()

# Element-wise multiplication to make scaled symmetric matrix
symmetric = np.round((non_symmetric.T * non_symmetric) / m**2)
print('Symmetric matrix')
print(symmetric)
print(symmetric.shape)
print()

# Vector
w = np.array([-1, 0, 1, 2])
print('Vector')
print(w)
print(w.shape)
print()

# Matrix-vector multiplication with symmetric matrix
print(symmetric @ w, (symmetric @ w).shape)  # (m by m) @ (m, 1) = (m, 1)
print(symmetric.T @ w, (symmetric.T @ w).shape)  # (m by m) @ (m, 1) = (m, 1)
print(w @ symmetric, (w @ symmetric).shape)  # (1 by m) @ (m, m) = (1, m)
print(w.T @ symmetric.T, (w.T @ symmetric.T).shape)  # (1 by m) @ (m, m) = (1, m)
print(w.T @ symmetric, (w.T @ symmetric).shape)  # (1 by m) @ (m, m) = (1, m)
print()

# Matrix-vector multiplication with non-symmetric matrix
print(non_symmetric @ w, (non_symmetric @ w).shape)  # (m by m) @ (m, 1) = (m, 1)
print(w.T @ non_symmetric.T, (w.T @ non_symmetric.T).shape)  # (1 by m) @ (m, m) = (1, m)
print(non_symmetric.T @ w, (non_symmetric.T @ w).shape)  # (m by m) @ (m, 1) = (m, 1)
print(w @ non_symmetric, (w @ non_symmetric).shape)  # (1 by m) @ (m, m) = (1, m)
print(w.T @ non_symmetric, (w.T @ non_symmetric).shape)  # (1 by m) @ (m, m) = (1, m)
print()

Non-symmetric matrix
[[ -6 -10   0   4]
 [ 10   8  -6  -7]
 [  9  -3  -2   3]
 [ -5 -10  -2   5]]
(4, 4)

Symmetric matrix
[[ 2. -6.  0. -1.]
 [-6.  4.  1.  4.]
 [ 0.  1.  0. -0.]
 [-1.  4. -0.  2.]]
(4, 4)

Vector
[-1  0  1  2]
(4,)

[-4. 15.  0.  5.] (4,)
[-4. 15.  0.  5.] (4,)
[-4. 15.  0.  5.] (4,)
[-4. 15.  0.  5.] (4,)
[-4. 15.  0.  5.] (4,)

[ 14 -30  -5  13] (4,)
[ 14 -30  -5  13] (4,)
[  5 -13  -6   9] (4,)
[  5 -13  -6   9] (4,)
[  5 -13  -6   9] (4,)

