# Rank

In [1]:
import numpy as np

In [10]:
m = 4
n = 6

A = np.random.randn(m, n)

ra = np.linalg.matrix_rank(A)
print(f'Rank A: {ra}')

B = A.copy()
print(f'id(A): {id(A)}, id(B): {id(B)}')

B[-1, :] = B[-2, :]
print('B')
print(np.round(B, 1))
print()

rb = np.linalg.matrix_rank(B)
print(f'Rank B: {rb}')

Rank A: 4
id(A): 1752809105232, id(B): 1752418781968
B
[[-0.6 -0.4  0.7 -1.8  1.2  0.2]
 [ 0.1 -1.8 -0.9  0.8 -0.6  1.3]
 [ 2.2 -1.  -0.5  0.2  0.4  0.9]
 [ 2.2 -1.  -0.5  0.2  0.4  0.9]]

Rank B: 3


## Noise

In [17]:
A = np.round(10 * np.random.randn(m, m))
A[:, -1] = A[:, -2]
print('A')
print(A)
print()

noises = [0.00000001, 0.00000000001, 0.00000000000000000001, 0.000000000000000000000000000000000000000001]

for noiseamp in noises:
    B = A + noiseamp * np.random.randn(m, m)

    print(f'Noise: {noiseamp}')
    print(f'Rank without noise: {np.linalg.matrix_rank(A)}')
    print(f'Rank with noise: {np.linalg.matrix_rank(B)}')
    print()

A
[[  6.   3.  -3.  -3.]
 [ -7.   2.  -1.  -1.]
 [-12. -14.   1.   1.]
 [ -4.  11.  -7.  -7.]]

Noise: 1e-08
Rank without noise: 3
Rank with noise: 4

Noise: 1e-11
Rank without noise: 3
Rank with noise: 4

Noise: 1e-20
Rank without noise: 3
Rank with noise: 3

Noise: 1e-42
Rank without noise: 3
Rank with noise: 3



## Rank by matrix multiplication
- Use matrix multiplication to create a 10x10 rank-4 matrix

In [21]:
A = np.random.randn(10, 4)
B = np.random.randn(4, 10)
C = A @ B
print('C')
print(C.shape)
print(f'Rank: {np.linalg.matrix_rank(C)}')
print()

# Generalize
m = 8
n = 47
r = 3

A = np.random.randn(m, r) @ np.random.randn(r, n)
print('A')
print(A.shape)
print(f'Rank: {np.linalg.matrix_rank(A)}')
print()

C
(10, 10)
Rank: 4

A
(8, 47)
Rank: 3



## Scalar multiplication
- Scalar multiplication with a matrix does not change the rank of the matrix
- Except 0 multiplication, because it makes 0 matrix, and rank of 0 matrix is 0.

In [33]:
m = 6
n = 4

# Full rank matrix
F = np.random.randn(m, n) * np.random.randn(n)

# Reduced rank matrix
R = np.random.randn(m, n - 1) @ np.random.randn(n - 1, m)

scalar = 12345

print(f'Full rank matrix rank: {np.linalg.matrix_rank(F)}')
print(f'Scalar multiplied full rank matrix rank: {np.linalg.matrix_rank(F * scalar)}')
print()
print(f'Reduced rank matrix rank: {np.linalg.matrix_rank(R)}')
print(f'Scalar multiplied reduced rank matrix rank: {np.linalg.matrix_rank(R * scalar)}')
print()

scalar = 0

print(f'Full rank matrix rank: {np.linalg.matrix_rank(F)}')
print(f'Scalar multiplied full rank matrix rank: {np.linalg.matrix_rank(F * scalar)}')
print()
print(f'Reduced rank matrix rank: {np.linalg.matrix_rank(R)}')
print(f'Scalar multiplied reduced rank matrix rank: {np.linalg.matrix_rank(R * scalar)}')
print()

Full rank matrix rank: 4
Scalar multiplied full rank matrix rank: 4

Reduced rank matrix rank: 3
Scalar multiplied reduced rank matrix rank: 3

Full rank matrix rank: 4
Scalar multiplied full rank matrix rank: 0

Reduced rank matrix rank: 3
Scalar multiplied reduced rank matrix rank: 0



## Rank of A^T A and A A^T

In [7]:
m = 14
n = 3

A = np.round(10 * np.random.randn(m, n))

AtA = A.T @ A
AAt = A @ A.T

print(f'AtA shape: {AtA.shape}, rank: {np.linalg.matrix_rank(AtA)}')
print(f'AAt shape: {AAt.shape}, rank: {np.linalg.matrix_rank(AAt)}')

AtA shape: (3, 3), rank: 3
AAt shape: (14, 14), rank: 3


## Rank of multiplied and summed matrices
- Use the following ideas
  - rank(A B) <= min(rank(A), rank(B))
  - rank(A + B) <= rank(A) + rank(B)

In [14]:
m = 2
n = 10

A = np.random.rand(m, n)
B = np.random.rand(m, n)

# Rank of A and B should be min of row and column
print(f'A.shape: {A.shape}, rank: {np.linalg.matrix_rank(A)}')
print(f'B.shape: {B.shape}, rank: {np.linalg.matrix_rank(B)}')

AtA = A.T @ A
BtB = B.T @ B

# Rank of AtA and BtB should be equal to the rank of A and B
print(f'AtA.shape: {AtA.shape}, rank: {np.linalg.matrix_rank(AtA)}')
print(f'BtB.shape: {BtB.shape}, rank: {np.linalg.matrix_rank(BtB)}')

# Finally see rank of multiplied and summed matrices
print(f'Rank(AtA BtB) should be 2: {np.linalg.matrix_rank(AtA @ BtB)}')
print(f'Rank(AtA + BtB) should be 4: {np.linalg.matrix_rank(AtA + BtB)}')

A.shape: (2, 10), rank: 2
B.shape: (2, 10), rank: 2
AtA.shape: (10, 10), rank: 2
BtB.shape: (10, 10), rank: 2
Rank(AtA BtB) should be 2: 2
Rank(AtA + BtB) should be 4: 4


## Create full-rank matrix by shifting

In [7]:
m = 30

A = np.random.randn(m, m)

# Make a symmetric matrix by A.T @ A for no reason, and scale up by multiplying 10, and rounding
A = np.round(10 * A.T @ A)

# Reduce rank
A[:, 0] = A[:, 1]

# Lambda for shifting by identity matrix
l = 0.01
B = A + l * np.eye(m, m)

print(f'Rank without shifting: {np.linalg.matrix_rank(A)}')
print(f'Rank with shifting to make full-rank: {np.linalg.matrix_rank(B)}')

Rank without shifting: 29
Rank with shifting to make full-rank: 30


## Determine whether a vector is in the span of set of vectors by rank
- A vector is in the span if the vector does not increase the rank of a matrix formed by the set of vectors
- A vector is not in the span if adding the vector to the matrix formed by the set of vectors increase the rank.

In [3]:
# First make a row vector, and make it column vector
v = np.array([
    [1, 2, 3, 4]
]).T
print(f'v.shape: {v.shape}')
print('v:')
print(v)
print()

S = np.vstack(([4, 3, 6, 2], [0, 4, 0, 1])).T
T = np.vstack(([1, 2, 2, 2], [0, 0, 1, 2])).T
print(f'S.shape: {S.shape}')
print(f'S:')
print(S)
print(f'Rank of S: {np.linalg.matrix_rank(S)}')
print()
print(f'T.shape: {T.shape}')
print('T:')
print(T)
print(f'Rank of T: {np.linalg.matrix_rank(T)}')
print()

Sv = np.concatenate((S, v), axis=1)
Tv = np.concatenate((T, v), axis=1)
print(f'Sv.shape: {Sv.shape}')
print('Sv')
print(Sv)
print('v seems to be not the linear combination of set of vectors,')
print('so it is expected to increase rank, so the augmenting vector is not in the span')
print(f'Rank of Sv: {np.linalg.matrix_rank(Sv)}')
print()

print(f'Tv.shape: {Tv.shape}')
print('Tv')
print(Tv)
print('v seems to be a linear combination of two vectors in the set,')
print('so it is expected not to increase the rank, so the vector is in the span of the set of vectors')
print(f'Rank of Tv: {np.linalg.matrix_rank(Tv)}')
print()

v.shape: (4, 1)
v:
[[1]
 [2]
 [3]
 [4]]

S.shape: (4, 2)
S:
[[4 0]
 [3 4]
 [6 0]
 [2 1]]
Rank of S: 2

T.shape: (4, 2)
T:
[[1 0]
 [2 0]
 [2 1]
 [2 2]]
Rank of T: 2

Sv.shape: (4, 3)
Sv
[[4 0 1]
 [3 4 2]
 [6 0 3]
 [2 1 4]]
v seems to be not the linear combination of set of vectors,
so it is expected to increase rank, so the augmenting vector is not in the span
Rank of Sv: 3

Tv.shape: (4, 3)
Tv
[[1 0 1]
 [2 0 2]
 [2 1 3]
 [2 2 4]]
v seems to be a linear combination of two vectors in the set,
so it is expected not to increase the rank, so the vector is in the span of the set of vectors
Rank of Tv: 2

