# Self-Adjoint Matrix

In [1]:
import numpy as np

In [9]:
m = 5

A = np.random.randn(m, m)
# Make it a symmetric matrix
A = A @ A.T

print('A')
print(np.round(A, 1))
print()

v = np.random.randn(m)
print('v')
print(np.round(v, 1))
print()

w = np.random.randn(m)
print('w')
print(np.round(w, 1))
print()

dot1 = np.dot(A @ v, w)
dot2 = np.dot(v, A @ w)
print(f'dot1: {dot1:.2f}, dot2: {dot2:.2f}')

A
[[ 1.4 -0.8  1.5  1.2  1.3]
 [-0.8  7.3  0.1 -2.9  4.1]
 [ 1.5  0.1  3.1  3.1  4. ]
 [ 1.2 -2.9  3.1  5.3  2.2]
 [ 1.3  4.1  4.   2.2  7.9]]

v
[-1.4  0.8  0.4 -1.4  0.4]

w
[-1.6  0.8  0.8 -0.7 -0.5]

dot1: 17.55, dot2: 17.55
