# Symmetric Matrix

In [1]:
import numpy as np
from sympy import *

## Additive method

In [5]:
m = 5
n = 5

a = np.random.randn(m, n)
print('Original matrix')
print(np.round(a, 1))
print()

symmetric = (a + a.T) / 2
print('Symmetric matrix')
print(np.round(symmetric, 1))
print()

Original matrix
[[ 0.3 -1.6 -0.8  1.  -1.3]
 [-1.1 -0.9 -0.1 -0.3  0.7]
 [ 0.4  2.2 -1.9 -0.3 -0.8]
 [ 2.2 -0.7  1.1  0.4 -1.2]
 [ 2.1 -2.2 -0.6 -1.  -0.8]]

Symmetric matrix
[[ 0.3 -1.4 -0.2  1.6  0.4]
 [-1.4 -0.9  1.  -0.5 -0.7]
 [-0.2  1.  -1.9  0.4 -0.7]
 [ 1.6 -0.5  0.4  0.4 -1.1]
 [ 0.4 -0.7 -0.7 -1.1 -0.8]]



## Multiplicative method

In [9]:
m = 5
n = 3

a = np.random.randn(m, n)
print('Original matrix')
print(np.round(a, 1))
print()

symmetric_1 = a.T @ a
print('Symmetric matrix')
print(np.round(symmetric_1, 1))
print()

symmetric_2 = a @ a.T
print('Symmetric matrix')
print(np.round(symmetric_2, 1))
print()

Original matrix
[[-0.8 -1.4  0.4]
 [ 1.4  1.6 -1.3]
 [ 1.8  0.1  1.6]
 [ 1.8  1.1  0.7]
 [ 0.3  0.7 -0.5]]

Symmetric matrix
[[ 9.5  5.8  1.9]
 [ 5.8  6.2 -2.1]
 [ 1.9 -2.1  5.1]]

Symmetric matrix
[[ 2.6 -3.9 -1.  -2.6 -1.4]
 [-3.9  6.4  0.8  3.4  2.3]
 [-1.   0.8  5.9  4.6 -0.1]
 [-2.6  3.4  4.6  5.   1. ]
 [-1.4  2.3 -0.1  1.   0.9]]



## Covariance matrix

In [19]:
m = 5
n = 3

a = np.random.randn(m, n)
print('Original matrix')
print(np.round(a, 1))
print()

cov = np.cov(a)
print('Covariance matrix')
print(np.round(cov, 1))
print()

symmetric = a @ a.T
print('Symmetric matrix')
print(np.round(symmetric, 1))
print()

Original matrix
[[ 0.6  1.6 -1. ]
 [-0.9 -0.2 -1.6]
 [ 0.2 -0.8 -1.6]
 [-0.  -1.3  1.2]
 [-1.1  1.1  0.4]]

Covariance matrix
[[ 1.8  1.   0.6 -1.7  0.3]
 [ 1.   0.5  0.3 -0.9  0.2]
 [ 0.6  0.3  0.8 -0.5 -0.8]
 [-1.7 -0.9 -0.5  1.6 -0.5]
 [ 0.3  0.2 -0.8 -0.5  1.3]]

Symmetric matrix
[[ 4.2  0.9  0.4 -3.5  0.7]
 [ 0.9  3.4  2.5 -1.7  0.2]
 [ 0.4  2.5  3.1 -0.8 -1.7]
 [-3.5 -1.7 -0.8  3.3 -0.9]
 [ 0.7  0.2 -1.7 -0.9  2.6]]



## Combined symmetric matrices

In [7]:
m = 3
A = np.random.randn(m, m)
AtA = A.T @ A

B = np.random.randn(m, m)
BtB = B.T @ B

# Sum
Cs = AtA + BtB

# Multiplication
Cm = AtA @ BtB

# Hadamard multiplication
Ch = AtA * BtB

print('Sum')
print(np.round(Cs, 1))
print(np.round(Cs - Cs.T, 1))
print()

print('Multiplication')
print(np.round(Cm, 1))
print(np.round(Cm - Cm.T, 1))
print()

print('Hadamard multiplication')
print(np.round(Ch, 1))
print(np.round(Ch - Ch.T, 1))
print()

Sum
[[ 4.3 -4.1 -0.2]
 [-4.1  8.1 -1.1]
 [-0.2 -1.1  1.1]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

Multiplication
[[  5.7 -15.2   5.5]
 [ -6.3  18.7  -6.8]
 [ -0.6   1.1  -0.4]]
[[ 0.  -8.9  6.1]
 [ 8.9  0.  -7.8]
 [-6.1  7.8  0. ]]

Hadamard multiplication
[[ 3.2  2.6 -0.2]
 [ 2.6 16.6 -0.5]
 [-0.2 -0.5  0.3]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]



In [11]:
a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u = symbols('a b c d e f g h i j k l m n o p q r s t u', real=True)

# Make symmetric matrices
A = Matrix([
    [a, b, c, d],
    [b, a, e, f],
    [c, e, a, h],
    [d, f, h, a]
])

B = Matrix([
    [l, m, n, o],
    [m, l, q, r],
    [n, q, l, t],
    [o, r, t, l]
])

# Confirm they are symmetric
print(A - A.T)
print(B - B.T)
print()

# Confirm diagonal elements are constant
for i in range(0, np.size(A, 0)):
    print(A[i, i])
print()

for i in range(0, np.size(B, 0)):
    print(B[i, i])
print()

Matrix([[0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0]])
Matrix([[0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0]])

a
a
a
a

l
l
l
l



In [13]:
init_printing()

# Because this does not produce zero matrix, the ouput matrix is not symmetric
A @ B - (A @ B).T

⎡          0             c⋅q + d⋅r - e⋅n - f⋅o   b⋅q + d⋅t - e⋅m - h⋅o   b⋅r +
⎢                                                                             
⎢-c⋅q - d⋅r + e⋅n + f⋅o            0             b⋅n - c⋅m + f⋅t - h⋅r   b⋅o -
⎢                                                                             
⎢-b⋅q - d⋅t + e⋅m + h⋅o  -b⋅n + c⋅m - f⋅t + h⋅r            0             c⋅o -
⎢                                                                             
⎣-b⋅r - c⋅t + f⋅m + h⋅n  -b⋅o + d⋅m - e⋅t + h⋅q  -c⋅o + d⋅n - e⋅r + f⋅q       

 c⋅t - f⋅m - h⋅n⎤
                ⎥
 d⋅m + e⋅t - h⋅q⎥
                ⎥
 d⋅n + e⋅r - f⋅q⎥
                ⎥
     0          ⎦

In [14]:
# Only 2 by 2 matrix produces symmetric matrix
n = 2
A1 = A[0:n, 0:n]
B1 = B[0:n, 0:n]

A1 @ B1 - (A1 @ B1).T

⎡0  0⎤
⎢    ⎥
⎣0  0⎦