# Symmetric Matrix

In [1]:
import numpy as np

## Additive method

In [5]:
m = 5
n = 5

a = np.random.randn(m, n)
print('Original matrix')
print(np.round(a, 1))
print()

symmetric = (a + a.T) / 2
print('Symmetric matrix')
print(np.round(symmetric, 1))
print()

Original matrix
[[ 0.3 -1.6 -0.8  1.  -1.3]
 [-1.1 -0.9 -0.1 -0.3  0.7]
 [ 0.4  2.2 -1.9 -0.3 -0.8]
 [ 2.2 -0.7  1.1  0.4 -1.2]
 [ 2.1 -2.2 -0.6 -1.  -0.8]]

Symmetric matrix
[[ 0.3 -1.4 -0.2  1.6  0.4]
 [-1.4 -0.9  1.  -0.5 -0.7]
 [-0.2  1.  -1.9  0.4 -0.7]
 [ 1.6 -0.5  0.4  0.4 -1.1]
 [ 0.4 -0.7 -0.7 -1.1 -0.8]]



## Multiplicative method

In [9]:
m = 5
n = 3

a = np.random.randn(m, n)
print('Original matrix')
print(np.round(a, 1))
print()

symmetric_1 = a.T @ a
print('Symmetric matrix')
print(np.round(symmetric_1, 1))
print()

symmetric_2 = a @ a.T
print('Symmetric matrix')
print(np.round(symmetric_2, 1))
print()

Original matrix
[[-0.8 -1.4  0.4]
 [ 1.4  1.6 -1.3]
 [ 1.8  0.1  1.6]
 [ 1.8  1.1  0.7]
 [ 0.3  0.7 -0.5]]

Symmetric matrix
[[ 9.5  5.8  1.9]
 [ 5.8  6.2 -2.1]
 [ 1.9 -2.1  5.1]]

Symmetric matrix
[[ 2.6 -3.9 -1.  -2.6 -1.4]
 [-3.9  6.4  0.8  3.4  2.3]
 [-1.   0.8  5.9  4.6 -0.1]
 [-2.6  3.4  4.6  5.   1. ]
 [-1.4  2.3 -0.1  1.   0.9]]



## Covariance matrix

In [19]:
m = 5
n = 3

a = np.random.randn(m, n)
print('Original matrix')
print(np.round(a, 1))
print()

cov = np.cov(a)
print('Covariance matrix')
print(np.round(cov, 1))
print()

symmetric = a @ a.T
print('Symmetric matrix')
print(np.round(symmetric, 1))
print()

Original matrix
[[ 0.6  1.6 -1. ]
 [-0.9 -0.2 -1.6]
 [ 0.2 -0.8 -1.6]
 [-0.  -1.3  1.2]
 [-1.1  1.1  0.4]]

Covariance matrix
[[ 1.8  1.   0.6 -1.7  0.3]
 [ 1.   0.5  0.3 -0.9  0.2]
 [ 0.6  0.3  0.8 -0.5 -0.8]
 [-1.7 -0.9 -0.5  1.6 -0.5]
 [ 0.3  0.2 -0.8 -0.5  1.3]]

Symmetric matrix
[[ 4.2  0.9  0.4 -3.5  0.7]
 [ 0.9  3.4  2.5 -1.7  0.2]
 [ 0.4  2.5  3.1 -0.8 -1.7]
 [-3.5 -1.7 -0.8  3.3 -0.9]
 [ 0.7  0.2 -1.7 -0.9  2.6]]

