# Eigenvector and Eigenvalue

## Dependency

In [1]:
import numpy as np

In [28]:
L = np.array([
    [0, 0, 0, 1],
    [1, 0, 0, 0],
    [0, 1, 0, 0],
    [0, 0, 1, 0]
])
eigenvals, eigenvecs = np.linalg.eig(L)
# print(f'Eigenvalue: {eigenvals.round(1)}')
# print(f'Eigenvector: {eigenvecs.round(1)}')

# Return the indices where absolute eigenvalues are descending order
order = np.absolute(eigenvals).argsort()[::-1]

# Reorder result
eigenvals = eigenvals[order]
eigenvecs = eigenvecs[:, order]

# Sets r to be the principal eigenvector
r = eigenvecs[:, 0]

print(eigenvals.round(2))
print(r)
print(np.sum(r))
print(100 * np.real(r / np.sum(r)))

[-1.+0.j  1.+0.j  0.-1.j  0.+1.j]
[-0.5+0.j  0.5+0.j -0.5+0.j  0.5+0.j]
0j
[-inf  inf -inf  inf]


C:\Users\YKITAY~1\AppData\Local\Temp/ipykernel_10248/72270533.py:24: RuntimeWarning: divide by zero encountered in true_divide
  print(100 * np.real(r / np.sum(r)))
C:\Users\YKITAY~1\AppData\Local\Temp/ipykernel_10248/72270533.py:24: RuntimeWarning: invalid value encountered in true_divide
  print(100 * np.real(r / np.sum(r)))


In [27]:
L = np.array([
    [0.1, 0.1, 0.1, 0.7],
    [0.7, 0.1, 0.1, 0.1],
    [0.1, 0.7, 0.1, 0.1],
    [0.1, 0.1, 0.7, 0.1]
])
eigenvals, eigenvecs = np.linalg.eig(L)
# print(f'Eigenvalue: {eigenvals.round(1)}')
# print(f'Eigenvector: {eigenvecs.round(1)}')

# Return the indices where absolute eigenvalues are descending order
order = np.absolute(eigenvals).argsort()[::-1]

# Reorder result
eigenvals = eigenvals[order]
eigenvecs = eigenvecs[:, order]

# Sets r to be the principal eigenvector
r = eigenvecs[:, 0]

print(eigenvals.round(2))
print(r)
print(np.sum(r))
print(100 * np.real(r / np.sum(r)))

[ 1. +0.j   0. -0.6j  0. +0.6j -0.6+0.j ]
[0.5+0.j 0.5+0.j 0.5+0.j 0.5+0.j]
(2+0j)
[25. 25. 25. 25.]


In [32]:
L = np.array([
    [0, 1, 0, 0],
    [1, 0, 0, 0],
    [0, 0, 0, 1],
    [0, 0, 1, 0]
])
r = 100 * np.ones(L.shape[0]) / L.shape[0] # Sets up this vector (6 entries of 1/6 × 100 each)
lastR = r
r = L @ r
i = 0
while np.linalg.norm(lastR - r) > 0.01 :
    lastR = r
    r = L @ r
    i += 1
print(str(i) + " iterations to convergence.")
r

0 iterations to convergence.


array([25., 25., 25., 25.])

In [34]:
L = np.array([
    [0, 1, 0, 0],
    [1, 0, 0, 0],
    [0, 0, 0, 1],
    [0, 0, 1, 0]
])

det = np.linalg.det(L)
print(f'Determinant: {det}')

eigenvals, eigenvecs = np.linalg.eig(L)
print(f'Eigenvalue: {eigenvals.round(1)}')
print(f'Eigenvector: {eigenvecs.round(1)}')

# Return the indices where absolute eigenvalues are descending order
order = np.absolute(eigenvals).argsort()[::-1]

# Reorder result
eigenvals = eigenvals[order]
eigenvecs = eigenvecs[:, order]

# Sets r to be the principal eigenvector
r = eigenvecs[:, 0]

print(eigenvals.round(2))
print(r)
print(np.sum(r))
print(100 * np.real(r / np.sum(r)))

Determinant: 1.0
Eigenvalue: [ 1. -1.  1. -1.]
Eigenvector: [[ 0.7 -0.7  0.   0. ]
 [ 0.7  0.7  0.   0. ]
 [ 0.   0.   0.7 -0.7]
 [ 0.   0.   0.7  0.7]]
[-1.  1. -1.  1.]
[ 0.          0.         -0.70710678  0.70710678]
0.0
[ nan  nan -inf  inf]


C:\Users\YKITAY~1\AppData\Local\Temp/ipykernel_10248/1964080954.py:28: RuntimeWarning: divide by zero encountered in true_divide
  print(100 * np.real(r / np.sum(r)))
C:\Users\YKITAY~1\AppData\Local\Temp/ipykernel_10248/1964080954.py:28: RuntimeWarning: invalid value encountered in true_divide
  print(100 * np.real(r / np.sum(r)))


In [37]:
A = np.array([
    [3/2, -1],
    [-1/2, 1/2]
])
coeffs = np.poly(A)
print(f'Characteristic polynomial coefficients: {coeffs}')

Characteristic polynomial coefficients: [ 1.   -2.    0.25]


In [38]:
A = np.array([
    [3/2, -1],
    [-1/2, 1/2]
])

C = np.array([
    [1 - np.sqrt(3), 1 + np.sqrt(3)],
    [1, 1]
])
A @ C

array([[-2.09807621,  3.09807621],
       [ 0.8660254 , -0.8660254 ]])